keys:
  - &albert age1rf75et6fud5duxrczv45vh05a6q0pvfep70h7cf33fdczku7jd2stem7rk

creation_rules:
  # User secrets
  - path_regex: ^users/[^/]+/secrets\.yaml$
    key_groups:
      - age:
          - *albert
  # Host secrets
  - path_regex: ^hosts/[^/]+/secrets\.yaml$
    key_groups:
      - age:
          - *albert
