# Auto-generated by imp - DO NOT EDIT
# Regenerate with: nix run .#imp-flake
{
  description = "Albert's NixOS configuration using imp";
  inputs = {
    # Enable git submodules
    self.submodules = true;

    # Core inputs
    flake-parts.url = "github:hercules-ci/flake-parts";
    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
    imp.url = "github:imp-nix/imp-nix";
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";

    # Collected from __inputs
    awww.url = "git+https://codeberg.org/LGFae/awww";
    awww.inputs.nixpkgs.follows = "nixpkgs";
    helium-browser.url = "github:Alb-O/helium-browser-flake";
    helium-browser.inputs.nixpkgs.follows = "nixpkgs";
    neovim-nightly-overlay.url = "github:nix-community/neovim-nightly-overlay";
    neovim-nightly-overlay.inputs.nixpkgs.follows = "nixpkgs";
    nix-colorizer.url = "github:nutsalhan87/nix-colorizer";
    nix-wallpaper.url = "github:lunik1/nix-wallpaper";
    nix-wallpaper.inputs.nixpkgs.follows = "nixpkgs";
    nixos-wsl.url = "github:nix-community/NixOS-WSL";
    nixos-wsl.inputs.nixpkgs.follows = "nixpkgs";
    nixpkgs-master.url = "github:NixOS/nixpkgs/master";
    nur.url = "github:nix-community/NUR";
    nur.inputs.nixpkgs.follows = "nixpkgs";
    oc-bin-flake.url = "github:bogorad/oc-bin-flake";
    oc-bin-flake.inputs.nixpkgs.follows = "nixpkgs";
    opencode-flake.url = "github:sst/opencode/v1.0.201";
    opencode-flake.inputs.nixpkgs.follows = "nixpkgs";
    sops-nix.url = "github:Mic92/sops-nix";
    sops-nix.inputs.nixpkgs.follows = "nixpkgs";
    stylix.url = "github:danth/stylix";
    stylix.inputs.nixpkgs.follows = "nixpkgs";
  };
  outputs = inputs: import ./flake inputs;
}
