# Auto-generated by imp - DO NOT EDIT
# Regenerate with: nix run .#imp-flake
{
  description = "Albert's NixOS configuration using imp";
  inputs = {
    # Core inputs
    flake-parts.url = "github:hercules-ci/flake-parts";
    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
    imp.url = "github:imp-nix/imp.lib";
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";

    # Collected from __inputs
    nixos-wsl.url = "github:nix-community/NixOS-WSL";
    nixos-wsl.inputs.nixpkgs.follows = "nixpkgs";
  };
  outputs = inputs: import ./nix/flake inputs;
}
